name: mostasmer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.3
  intl: ^0.19.0
  get: ^4.6.6
  easy_localization: ^3.0.7
  hexcolor: ^3.0.1
  flutter_otp_text_field: ^1.2.0
  flutter_svg: ^2.0.16
  syncfusion_flutter_sliders: ^28.1.33
  dropdown_button2: ^2.3.9
  tab_indicator_styler: ^2.0.0
  buttons_tabbar: ^1.3.14
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_swiper_view: ^1.1.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/launcherIcon/app_launcher_icon.png'
  adaptive_icon_forground: "assets/launcherIcon/app_launcher_icon.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21



flutter:


  uses-material-design: true

  assets:
     - assets/
     - assets/lang/
     - assets/navbar/
     - assets/launcherIcon/app_launcher_icon.png
     - assets/Splash.png
     - assets/onboarding.png
     - assets/lang/ar.json
     - assets/lang/en.json
     - assets/error.png
     - assets/images/



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
